# Generated by Django 6.0.4 on 2026-05-08 05:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('address', models.TextField()),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='bus',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seat',
            name='bus',
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='conductor_name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='conductor_phone',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='driver_phone',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='route',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='bus',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('ac_seater', 'AC Seater'), ('ac_sleeper', 'AC Sleeper'), ('non_ac_seater', 'Non-AC Seater'), ('non_ac_sleeper', 'Non-AC Sleeper'), ('volvo', 'Volvo AC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days_of_week',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=50),
        ),
        migrations.CreateModel(
            name='BusInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspection_type', models.CharField(choices=[('daily', 'Daily Check'), ('weekly', 'Weekly Inspection'), ('monthly', 'Monthly Inspection'), ('annual', 'Annual Inspection')], max_length=50)),
                ('inspected_by', models.CharField(max_length=100)),
                ('inspection_result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional Pass')], max_length=20)),
                ('issues_found', models.TextField(blank=True)),
                ('next_inspection_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='bus_management.bus')),
            ],
            options={
                'verbose_name': 'Bus Inspection',
                'verbose_name_plural': 'Bus Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='BusPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('total_km_driven', models.FloatField(help_text='Total kilometers driven')),
                ('total_trips', models.IntegerField(help_text='Number of trips completed')),
                ('total_passengers', models.IntegerField(help_text='Total passengers carried')),
                ('total_revenue', models.DecimalField(decimal_places=2, help_text='Total revenue generated', max_digits=12)),
                ('fuel_consumed', models.FloatField(help_text='Total fuel consumed in liters')),
                ('average_speed', models.FloatField(help_text='Average speed in km/h')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='bus_management.bus')),
            ],
            options={
                'verbose_name': 'Bus Performance',
                'verbose_name_plural': 'Bus Performance Records',
                'ordering': ['-record_date'],
                'unique_together': {('bus', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='BusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bus_management.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bus_management.driver')),
            ],
            options={
                'verbose_name': 'Bus Assignment',
                'verbose_name_plural': 'Bus Assignments',
                'unique_together': {('bus', 'driver', 'assigned_date')},
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='bus_management.driver'),
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_date', models.DateField()),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('electric', 'Electric')], max_length=20)),
                ('fuel_quantity', models.FloatField(help_text='Fuel quantity in liters')),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_reading', models.IntegerField(help_text='Odometer reading in km')),
                ('fuel_station', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='bus_management.bus')),
            ],
            options={
                'verbose_name': 'Fuel Record',
                'verbose_name_plural': 'Fuel Records',
                'ordering': ['-fuel_date'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='bus_management.bus')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance Records',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(help_text='Order of stops in the route')),
                ('distance_from_start', models.FloatField(help_text='Distance from route start in km')),
                ('estimated_arrival', models.TimeField(help_text='Estimated arrival time from start')),
                ('is_active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='bus_management.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='bus_management.stop')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['sequence_number'],
                'unique_together': {('route', 'stop')},
            },
        ),
        migrations.DeleteModel(
            name='BusLocation',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
